### PR TITLE
Blender 2.8 changes

### PR DESCRIPTION
**Pull request by johnakki**
Mainly moved/deprecated methods and deprecated handlers. Object layer code is just commented out for now so the addon actually works, but needs editing to use collections. Cycles visibility doesn't apply to EEVEE so visibility will need changing to target the object's parent collection.
Anyway, it basically works now. [0029](https://user-images.githubusercontent.com/6125252/41203708-e58a440e-6cd2-11e8-8cb7-2cdb02aafdac.png)
Animations are currently broken in Blender 2.8 so use something like this if you want to do any testing:
for i in range(1,90):
	bpy.context.scene.frame_set(i)
	bpy.ops.render.render(animation=False, write_still=True, use_viewport=True)

### CODE REVIEW

**Comment by rlguy** [comment]
Hey johnakki,

Thanks for taking time to look at the code and make corrections. Unfortunately we will not be accepting pull requests for this repository. I am sorry that this was not explained in any of the project documentation. I have opened a documentation request to add a ```CONTRIBUTING.md``` file here: #335 

> Pull requests will not likely be accepted for this repository. This is because the main FLIP Fluids branch is located in a private repository and will often be further ahead in development than this public repository. This public repository will not be receiving updates and bug fixes as frequently as the product located on the Blender Market page. Due to licensing restrictions, it will be difficult/complicated for us to keep this public repository completely in sync with the main branch.

The main branch is quite a bit further ahead of this repository at the moment. We are actually in progress of making changes to support Blender 2.8 and are paying careful attention to ensure that both 2.79 and 2.8 are supported within the same build.

\- Ryan

**Comment by johnakki** [comment]
No problem at all , it's been good python practice and it might give me the kick I need to start working on one or two addons of my own.
Thank you for open sourcing this project and well done for what you've managed to achieve. I can't even begin to understand what's going on in your fluid engine but the resulting simulations are really amazing.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rlguy** [comment]
Hello philstopford,

Some licensing information can be found here: [FAQ: How is the FLIP Fluids addon licensed?](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#how-is-the-flip-fluids-addon-licensed)

The entire codebase is GPL compliant. The addon code is licensed under the GPL, which is a requirement of Blender addons. The engine code is licensed under MIT, and this is compatible with the addon GPL code since the engine does not depend on any Blender code. The reason for the engine being licensed as MIT is so that the code can be completely removed from the addon and used with no restrictions by other developers. We have had interest from other developers wanting to port the engine to other sofware, so this is why we made that decision.

What is not open source is content such as .blend files, materials, and data that have been created by other artists that are used in this addon. These files are licensed under a Standard Royalty Free license and we cannot distribute these on a public repository. That is why features that depend on these files have been removed in the public repository. This is still GPL compliant as artwork/data is not covered by the GPL license.

For paying customers, you will find the full source code including data/artwork within the addon installation .zip file under the directory named ```source```. As this version of the source code contains Royalty Free content, it cannot be distributed to others legally unless this content is first removed.

Hope this clarifies concerns with the licensing!

\- Ryan

**Comment by philstopford** [comment]
OK, so we should at least be able to build the same combination of MIT and GPL code to match any given release; that's the bit that concerned me. That's covered by the source.zip approach, so I'm OK. Thanks for the reply - it helps a lot.

**Pull request closed without merging**
